# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-05 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_name', models.CharField(max_length=30)),
                ('Department', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Dateofbirth', models.DateField()),
                ('Picture', models.ImageField(blank=True, upload_to='staff/media/images')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='staff.Employee'),
        ),
    ]
